### ISSUE TITLE
Why non ASCII characters are not allowed in student submissions?

### ISSUE THREAD

**Issue by dz0** [daveagp/websheets#6]
Some examples in our uni use Lithuanian letters (non-ASCII), but websheets filters for them.. 

What is the reason behind [this](https://github.com/daveagp/websheets/blob/df091d75d9ba3a6580d5de01adf6d6c4c9b5d3cd/submit.py#L64)?

**Comment by daveagp** [comment]
You are right that the given check is not a great idea.

The main reason for the check is that students would sometimes submit code with smart quotes or non-printing blank characters and they'd get confused when it does not compile. 

I'll think about doing it a better way.

**Comment by daveagp** [comment]
I've tried to make it only single out smart quotes and unprintable characters in the 0..255 range. take a look: https://github.com/daveagp/websheets/commit/3ca4607ae8a98674dc7b69f2f95d27ad3ecb9a9e

**Comment by dz0** [comment]
"C++ call functions directly" mode still has issues (even thouhg nonascii chars are in comments)
see example, http://cscircles.cemc.uwaterloo.ca/websheets/editor.php?edit=cpp/ktu/2/kelione

ps.: not urgent :)

**Comment by daveagp** [comment]
Thanks! Fixed by: https://github.com/daveagp/websheets/commit/3ce2a2edf16f549690f992fb611c1ba312c6262f

BTW I also tried turning on -fextended-identifiers and even upgrading to gcc 4.7 which seems as far as I can easily get on our centos 5 machine, but it still didn't seem to be possible to use accents in variable names.

**Comment by dz0** [comment]
Tab's are still not allowed :/

```
Syntax error: Your code contains character number 9:
…() {
	
}
```

When in http://cscircles.cemc.uwaterloo.ca/websheets/?folder=cpp&start=scratch just copied "	" inside..

ps.: This usually happens when students develop programs in IDE's (for debugging purposes), and copy results back.

**Comment by daveagp** [comment]
Should now be fixed, e53d738868f9cb861771bfcce4910188e8b82172

**Comment by dz0** [comment]
That's what could be called a quick-fix :)

**Comment by daveagp** [comment]
I happen to be in Waterloo for the day so I didn't have to wait for the light to travel very far :speedboat:
